[package]
name = "non_bin"
version = "0.1.0"
authors = ["Spenser Saling <spenser@brainiumstudios.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
